=== cs0320/cs0320.github.io/src/data/lectures.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "id": {
        "type": "integer",
        "exclusiveMinimum": 0,
        "maximum": 9007199254740991
      },
      "date": {
        "type": "string",
        "pattern": "^\\d{2}\\/\\d{2} [MWF]$"
      },
      "topic": {
        "type": "string",
        "minLength": 1
      },
      "notes": {
        "anyOf": [
          {
            "type": "string",
            "const": ""
          },
          {
            "type": "string",
            "format": "uri"
          }
        ]
      },
      "code": {
        "anyOf": [
          {
            "type": "string",
            "const": ""
          },
          {
            "type": "string",
            "format": "uri"
          }
        ]
      },
      "recording": {
        "anyOf": [
          {
            "type": "string",
            "const": ""
          },
          {
            "type": "string",
            "format": "uri"
          }
        ]
      },
      "readings": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "title": {
              "type": "string",
              "minLength": 1
            },
            "url": {
              "anyOf": [
                {
                  "type": "string",
                  "const": ""
                },
                {
                  "type": "string",
                  "format": "uri"
                }
              ]
            }
          },
          "required": [
            "title",
            "url"
          ],
          "additionalProperties": false
        }
      }
    },
    "required": [
      "id",
      "date",
      "topic",
      "notes",
      "code",
      "recording",
      "readings"
    ],
    "additionalProperties": false
  }
}

=== cs0320/cs0320.github.io/src/data/lectures.json
[
  {
    "id": 1,
    "date": "09/09 W",
    "topic": "Success in 0320",
    "notes": "https://cs0320.github.io/notes/latest/success-in-0320/success-in-0320.html",
    "code": "",
    "recording": "https://brown.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=305a6e5d-47c2-4979-ab9a-b4ba013c36a6",
    "readings": [{"title": "Missive", "url": "https://docs.google.com/document/d/1SlciWB344FHta0zwQWC-QGS7CR5ybAl4HYg4Prl7wqw"}]
  },
  {
    "id": 2,
    "date": "09/11 F",
    "topic": "TypeScript, Security Feedback",
    "notes": "",
    "code": "https://github.com/cs0320/class-livecode/tree/main/F26/sep11",
    "recording": "https://brown.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=7e2876da-8648-4b7a-9b7c-b4ba013c36f1",
    "readings": []
  },
  {
    "id": 3,
    "date": "09/14 M",
    "topic": "Properties",
    "notes": "https://cs0320.github.io/notes/latest/02-properties/02-properties.html",
    "code": "",
    "recording": "https://brown.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=cacb23e7-ca35-4f92-95cf-b4ba013c3709",
    "readings": [{"title": "1710 Notes", "url": "https://forge-fm.github.io/book/2026/chapters/properties/pbt.html"},
                 {"title": "Choosing Properties", "url": "https://fsharpforfunandprofit.com/posts/property-based-testing-2/"}]
  },
  {
    "id": 4,
    "date": "09/16 W",
    "topic": "Validation",
    "notes": "https://cs0320.github.io/notes/latest/03-bias-validation/03-bias-validation.html",
    "code": "https://github.com/cs0320/class-livecode/tree/main/F26/sep16",
    "recording": "https://brown.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=3328ecd0-1e73-4710-8e5a-b4ba013c3721",
    "readings": []
  },
  {
    "id": 5,
    "date": "09/18 F",
    "topic": "Zod, Async",
    "notes": "https://cs0320.github.io/notes/latest/03-bias-validation/03-bias-validation.html",
    "code": "https://github.com/cs0320/class-livecode/tree/main/F26/sep18",
    "recording": "https://brown.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=bed86759-fec9-42c9-83d0-b4ba013c373c",
    "readings": [{"title": "Types Chapter", "url": "https://docs.google.com/document/d/1OsWdY3DbnnK9faoT0M6hdI6bUa8gGi2TP2ti7hsap90/edit?usp=sharing"}]
  },
  {
    "id": 6,
    "date": "09/21 M",
    "topic": "Zod, State Machines",
    "notes": "",
    "code": "https://github.com/cs0320/class-livecode/tree/main/F26/sep21",
    "recording": "https://brown.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=95e5ee6a-0c06-4152-a04d-b4ba013c3754",
    "readings": []
  },
  {
    "id": 7,
    "date": "09/23 W",
    "topic": "H.O. functions to build classes",
    "notes": "",
    "code": "https://github.com/cs0320/class-livecode/tree/main/F26/sep23",
    "recording": "https://brown.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=809163c7-2c92-4495-a5f1-b4ba013c3767",
    "readings": []
  },
  {
    "id": 8,
    "date": "09/25 F",
    "topic": "Mocking",
    "notes": "",
    "code": "https://github.com/cs0320/class-livecode/tree/main/F26/sep25",
    "recording": "https://brown.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=03d0c60c-23e2-41b9-98a3-b4ba013c3780",
    "readings": []
  },
  {
    "id": 9,
    "date": "09/28 M",
    "topic": "Web APIs and Arbitraries",
    "notes": "https://cs0320.github.io/notes/latest/05-apis/05-apis.html",
    "code": "",
    "recording": "https://brown.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=60dac8af-8c4d-4ba8-a94a-b4ba013c3796",
    "readings": [{"title": "Not Inevitable", "url": "https://blog.cs.brown.edu/2026/09/25/ellie-pavlick-weighs-in-on-aria-and-the-future-of-ai/"}]
  },
  {
    "id": 10,
    "date": "09/30 W",
    "topic": "GUEST: Viktor Gavrielov '15 (Career Ctr)",
    "notes": "",
    "code": "",
    "recording": "https://brown.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=a7400b1c-7f69-447c-8599-b4ba013c37a9",
    "readings": []
  },
  {
    "id": 11,
    "date": "10/02 F",
    "topic": "GUEST: Sam Dooman (DownDog)",
    "notes": "",
    "code": "",
    "recording": "https://brown.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=6cb09137-b931-438b-9ffe-b4ba013c37c1",
    "readings": [{"title": "B* Fellowship", "url": "https://blog.cs.brown.edu/2026/04/06/inspiring-alums-sam-dooman-supports-entrepreneurs-while-building-consumer-software/"}]
  },
  {
    "id": 12,
    "date": "10/05 M",
    "topic": "Security: API Fuzzing",
    "notes": "",
    "code": "",
    "recording": "https://brown.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=78bac627-c746-426c-ac7e-b4ba013c37db",
    "readings": [{"title": "Slides (Brown only)", "url":"https://docs.google.com/presentation/d/1rvPU5GXQpydb7TaX3Ixi6rSy86zMCINV4CUd5ZPYxrs/edit?usp=sharing"}]
  },
  {
    "id": 13,
    "date": "10/07 W",
    "topic": "Webdev and React",
    "notes": "https://cs0320.github.io/notes/latest/06-html-react/06-html-react.html",
    "code": "",
    "recording": "https://brown.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=2e214a72-9dc6-4c63-b51c-b4ba013c37f2",
    "readings": []
  },
  {
    "id": 14,
    "date": "10/09 F",
    "topic": "Term Project Discussion",
    "notes": "",
    "code": "",
    "recording": "https://brown.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=a0bf0415-ac9a-4a7b-ab3f-b4ba013c380a",
    "readings": [{"title": "Ideas Thread", "url":"https://edstem.org/us/courses/98017/discussion/8372316"}]
  },
  {
    "id": 15,
    "date": "10/14 W",
    "topic": "Sprint 5 Discussion",
    "notes": "",
    "code": "",
    "recording": "",
    "readings": []
  },
  {
    "id": 16,
    "date": "10/16 F",
    "topic": "UI Design and Frogs",
    "notes": "https://docs.google.com/presentation/d/1JGeoF33UkHk2HptM67xIqufIqByKmgVT1KdSHg8ExlE/edit?usp=sharing",
    "code": "",
    "recording": "",
    "readings": [{"title": "Flexbox Froggy", "url": "https://flexboxfroggy.com/"}]
  },
  {
    "id": 17,
    "date": "10/19 M",
    "topic": "Cloud and Storage",
    "notes": "",
    "code": "",
    "recording": "",
    "readings": []
  },
  {
    "id": 18,
    "date": "10/21 W",
    "topic": "TBD",
    "notes": "",
    "code": "",
    "recording": "",
    "readings": []
  },
  {
    "id": 19,
    "date": "10/23 F",
    "topic": "TBD",
    "notes": "",
    "code": "",
    "recording": "",
    "readings": []
  },
  {
    "id": 20,
    "date": "10/26 M",
    "topic": "TBD",
    "notes": "",
    "code": "",
    "recording": "",
    "readings": []
  },
  {
    "id": 21,
    "date": "10/28 W",
    "topic": "TBD",
    "notes": "",
    "code": "",
    "recording": "",
    "readings": []
  },
  {
    "id": 22,
    "date": "10/30 F",
    "topic": "TBD",
    "notes": "",
    "code": "",
    "recording": "",
    "readings": []
  },
  {
    "id": 23,
    "date": "11/02 M",
    "topic": "TBD",
    "notes": "",
    "code": "",
    "recording": "",
    "readings": []
  },
  {
    "id": 24,
    "date": "11/04 W",
    "topic": "TBD",
    "notes": "",
    "code": "",
    "recording": "",
    "readings": []
  },
  {
    "id": 25,
    "date": "11/06 F",
    "topic": "TBD",
    "notes": "",
    "code": "",
    "recording": "",
    "readings": []
  },
  {
    "id": 26,
    "date": "11/09 M",
    "topic": "TBD",
    "notes": "",
    "code": "",
    "recording": "",
    "readings": []
  },
  {
    "id": 27,
    "date": "11/11 W",
    "topic": "TBD",
    "notes": "",
    "code": "",
    "recording": "",
    "readings": []
  },
  {
    "id": 28,
    "date": "11/13 F",
    "topic": "TBD",
    "notes": "",
    "code": "",
    "recording": "",
    "readings": []
  },
  {
    "id": 29,
    "date": "11/16 M",
    "topic": "TBD",
    "notes": "",
    "code": "",
    "recording": "",
    "readings": []
  },
  {
    "id": 30,
    "date": "11/18 W",
    "topic": "TBD",
    "notes": "",
    "code": "",
    "recording": "",
    "readings": []
  },
  {
    "id": 31,
    "date": "11/20 F",
    "topic": "TBD",
    "notes": "",
    "code": "",
    "recording": "",
    "readings": []
  },
  {
    "id": 32,
    "date": "11/23 M",
    "topic": "Optional: Future of 0320 Dev",
    "notes": "",
    "code": "",
    "recording": "",
    "readings": []
  },
  {
    "id": 33,
    "date": "11/30 M",
    "topic": "TBD (Possible Guest)",
    "notes": "",
    "code": "",
    "recording": "",
    "readings": []
  },
  {
    "id": 34,
    "date": "12/02 W",
    "topic": "TBD (Possible Guest)",
    "notes": "",
    "code": "",
    "recording": "",
    "readings": []
  },
  {
    "id": 35,
    "date": "12/04 F",
    "topic": "GUEST: Tim Ross (Teleport)",
    "notes": "",
    "code": "",
    "recording": "",
    "readings": []
  },
  {
    "id": 36,
    "date": "12/07 M",
    "topic": "GUEST: Salman Saghafi (Mimic): WASM",
    "notes": "",
    "code": "",
    "recording": "",
    "readings": []
  }
]
